# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
stages: 
 - stage: Build
   displayName: Build stage
   jobs:
     - job: MavenPackageAndPublishArtifacts
       displayName: Maven Package and Publish Artifacts
       steps:
        - task: Maven@3
          displayName: 'Maven Package'
          inputs:
            mavenPomFile: 'pom.xml'
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: '1.11'
            jdkArchitectureOption: 'x64'
 - stage: Test
   displayName: Test
   jobs:
     - job: RunTest
       displayName: Run Test
       steps:
         - task: Maven@3
           displayName: Maven Test
           inputs:
            mavenPomFile: 'pom.xml'
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: '1.11'
            jdkArchitectureOption: 'x64'
            testRunTitle: UnitTest
            testResultsFiles: "Test*.xml"

 - stage: CopyFile
   displayName: CopyFile
   jobs:
     - job: CopyFileToDrop
       displayName: CopyFileToDrop
       steps:
        - task: CopyFiles@2
          displayName: 'Copy Files to artifact staging directory'
          inputs:
            SourceFolder: '$(System.DefaultWorkingDirectory)'
            Contents: '**/target/*.?(war|jar)'
            TargetFolder: $(Build.ArtifactStagingDirectory)

        - upload: $(Build.ArtifactStagingDirectory)
          artifact: drop